[package]
name = "swarm"
version = "0.1.0"
authors = ["Satya Bodduluri <skbodduluri@gmail.com>"]
build = "build.rs"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
hyper = "0.8.0"
time = "0.1"
yaml-rust = "*"
libc = "0.2"

[build-dependencies]
gcc = "0.3"